server.port=9091

spring.datasource.url=jdbc:mysql://localhost:3306/aura?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

spring.security.oauth2.client.registration.google.client-id=907736386931-3mr1ujqju1irkfqf8i96gqp4vrq9ah7t.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,email,profile,https://www.googleapis.com/auth/gmail.readonly,https://www.googleapis.com/auth/gmail.send,https://www.googleapis.com/auth/gmail.modify
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/google
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.scope=email,profile,https://www.googleapis.com/auth/gmail.readonly
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth?access_type=offline&prompt=consent
gemini.api.key=AIzaSyCscXTMfIa7mzabSMSQPyKYeNGCRn_pPSM
razorpay.key.id=rzp_test_StyfzfGviH6ONQ
razorpay.key.secret=xt2DHExFWD0TnnNFLXaxSwQO
aura.gmail.max-results=50
spring.web.resources.static-locations=classpath:/static/
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aasishsharma0901@gmail.com
spring.mail.password=uipkmrhpvjeswskh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true